package base.location;

public enum PlaceType {
    ACCOUNTING, AIRPORT, ATM, BANK,
    BAR, BEAUTY_SALON, CAFE, CAR_DEALER,
    DENTIST, DRUGSTORE, EMBASSY, GAS_STATION,
    GYM, HAIR_CARE, HOSPITAL, LIBRARY,
    MOVIE_THEATER, MUSEUM, OTHER, PARK,
    POST_OFFICE, RESTAURANT, SCHOOL, SHOPPING_MALL,
    STADIUM, SUBWAY_STATION,
    TRAIN_STATION, UNIVERSITY, ZOO,
}
